language: python

sudo: false

python:
    - "3.4"
    - "3.5"

cache:
    apt: true
    pip: true

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran

notifications:
  email: false

install:
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel
    - pip install -e .

script: python orangecontrib/interactions/tests/test_interactions.py
